//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVietTien.SachOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SACH
    {
        public SACH()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.VIETSACHes = new HashSet<VIETSACH>();
        }

        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaNXB { get; set; }
    
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual ICollection<VIETSACH> VIETSACHes { get; set; }
    }
}
